### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by electromechpro** [RoanokeControls/PkgUltrasonicUSBDemo#1]
11/14/23 Attempting to install UltrasonicUSBDemo on a Windows 10 PC per printed as well as github instructions, starting with installing Python ver  3.12.  I copied and pasted in the 2 commands, "pip install UltrasonicUSBDemo" ran, but "python -m UltrasonicUSBDemo" returned 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\g.cawthon\AppData\Local\Programs\Python\Python312\Lib\site-packages\UltrasonicUSBDemo\__main__.py", line 3, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

Can you advise how to proceed please?
Thank you.

**Comment by BrodyOlabarriaga** [comment]
Hi, did you ever resolve this? I have the same unit and cannot seem to receive values. Cheers
